from __future__ import annotations

import json
from pathlib import Path

from .errors import ProcessError
from .io import digest_file


GENERATED_MARKER = "<!-- GENERATED BY software-engineering-process; DO NOT EDIT. -->"


def bootstrap(manifest: dict, assistant: str) -> str:
    p = manifest["process"]
    title = "Codex" if assistant == "codex" else "Claude Code" if assistant == "claude" else "Engineering participant"
    local_context = manifest.get("local_context", [])
    context_lines = "\n".join(
        f"- `{item['path']}` ({item['category']}): {item.get('load_when', 'load when relevant to the change')}"
        for item in local_context
    ) or "- None declared."
    return f"""{GENERATED_MARKER}
# {title} engineering bootstrap

Process: `{p['source']}` `{p['version']}` @ `{p['revision']}`  
Profile: `{p['profile']}` · Manifest: `.engineering/process.yaml`

Before changing code, run `engineering-process classify` and `engineering-process evaluate`.
Follow the resolved Effective Obligation Set; load only its selected Skills.

Repository-owned local context (adds mechanics/detail; never overrides canonical policy):
{context_lines}

Non-negotiable boundaries:
- Keep issue/change traceability and work only within approved scope.
- Never expose or commit secrets or private data.
- Protected ambiguity fails closed; deterministic sensitive signals cannot be downgraded.
- Final independent review must use a fresh context, separate from implementation.
- Evidence must be machine-readable and bound to the exact target and process revisions.
- Production approval remains human-controlled and cannot be self-approved.

The policy owns what must be true. Use native {title}, CI, GitHub, and human mechanisms for how.
Do not edit this file; run `engineering-process render`.
"""


def is_generated_bootstrap(path: Path) -> bool:
    return path.is_file() and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER)


def render_files(root: Path, manifest: dict, allow_create: bool = True) -> dict[str, str]:
    files = {"AGENTS.md": bootstrap(manifest, "codex"), "CLAUDE.md": bootstrap(manifest, "claude")}
    for name, text in files.items():
        path = root / name
        if path.exists() and not is_generated_bootstrap(path):
            raise ProcessError(f"refusing to overwrite repository-owned context: {name}; use init --adopt-existing-context")
        if not path.exists() and not allow_create:
            raise ProcessError(f"generated adapter is missing: {name}")
        path.write_text(text, encoding="utf-8")
    return {name: digest_file(root / name) for name in files}


def metrics(root: Path, selected_skills: list[str] | None = None) -> dict:
    result = {}
    for name in ("AGENTS.md", "CLAUDE.md"):
        if (root / name).exists():
            text = (root / name).read_text(encoding="utf-8")
            result[name] = {"bytes": len(text.encode()), "words": len(text.split()), "approx_tokens": round(len(text) / 4)}
    result["activated_skills"] = len(selected_skills or [])
    return result
