from __future__ import annotations

import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import yaml

from .errors import ProcessError
from .io import canonical_json, digest_bytes, digest_file, load_json, load_yaml, write_json
from .paths import skills_root
from .paths import policy_root
from .policy import load_policy, validate_overrides
from .render import is_generated_bootstrap, render_files


ASSISTANT_FILES = ("AGENTS.md", "CLAUDE.md")


def _relative_posix(path: Path, root: Path) -> str:
    """Return a portable repository-relative path for persisted metadata."""
    return path.relative_to(root).as_posix()


def _workflow_text(revision: str) -> str:
    return f"""# GENERATED BY software-engineering-process; DO NOT EDIT.\nname: Engineering process\non: [pull_request, push]\npermissions:\n  contents: read\njobs:\n  validate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with: {{fetch-depth: 0}}\n      - uses: actions/setup-python@v5\n        with: {{python-version: '3.12'}}\n      - run: pip install 'git+https://github.com/suyog19/software-engineering-process@{revision}'\n      - run: engineering-process validate --runtime-revision '{revision}'\n"""


def _adopt_context(root: Path) -> list[dict]:
    context = []
    destination = root / "docs" / "engineering" / "local-context"
    candidates = [(root / name, destination / f"{Path(name).stem.lower()}-legacy.md") for name in ASSISTANT_FILES
                  if (root / name).exists() and not is_generated_bootstrap(root / name)]
    collisions = [target for _, target in candidates if target.exists()]
    if collisions:
        raise ProcessError("adoption destination already exists: " + ", ".join(str(path.relative_to(root)) for path in collisions))
    for source, target in candidates:
        destination.mkdir(parents=True, exist_ok=True)
        source.replace(target)
        context.append({"category": "operating_contract", "path": target.relative_to(root).as_posix(),
                        "load_when": "load before planning or changing repository behavior"})
    return context


def _assert_owned(root: Path, lock: dict, relative: str) -> None:
    path = root / relative
    expected = lock.get("generated_files", {}).get(relative)
    if not path.exists() or not expected or digest_file(path) != expected:
        raise ProcessError(f"refusing to overwrite repository-owned or modified file: {relative}")


def current_revision(root: Path) -> str:
    result = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, text=True, capture_output=True)
    sha = result.stdout.strip()
    if result.returncode or len(sha) != 40:
        raise ProcessError("cannot resolve process Git revision; provide --revision")
    return sha


def initialize(root: Path, profile: str, repository_name: str, revision: str, force: bool = False,
               adopt_existing_context: bool = False) -> dict:
    engineering = root / ".engineering"
    manifest_path = engineering / "process.yaml"
    if manifest_path.exists():
        if force:
            raise ProcessError("--force cannot replace an initialized repository; use engineering-process upgrade")
        raise ProcessError(f"already initialized: {manifest_path}")
    existing = [name for name in ASSISTANT_FILES if (root / name).exists() and not is_generated_bootstrap(root / name)]
    if existing and not adopt_existing_context:
        raise ProcessError("existing repository-owned context would be overwritten: " + ", ".join(existing) +
                           "; review it, then rerun with --adopt-existing-context")
    workflow = root / ".github" / "workflows" / "process-validation.yml"
    if workflow.exists() and not workflow.read_text(encoding="utf-8").startswith("# GENERATED BY software-engineering-process"):
        raise ProcessError("refusing to overwrite repository-owned file: .github/workflows/process-validation.yml")
    reserved = [engineering / "process.lock", engineering / "skills", engineering / "generated" / "resolved-policy.json"]
    conflicts = [path.relative_to(root) for path in reserved if path.exists()]
    if conflicts:
        raise ProcessError("refusing to overwrite existing process target: " + ", ".join(map(str, conflicts)))
    local_context = _adopt_context(root) if adopt_existing_context else []
    core, selected_profile, delivery = load_policy(policy_root(), profile)
    process_version = core["process"]["version"]
    manifest = {"schema_version": 2, "process": {"source": "suyog19/software-engineering-process", "version": process_version, "revision": revision, "profile": profile}, "repository": {"name": repository_name}, "overrides": {"validation": {"commands": []}}, "adoption": {"target_mode": "Foundation", "metrics_enabled": False}, "adapters": {"github": {"readiness_status": "engineering-process", "protected_branch": "main", "production_environment": "production", "runner_labels": ["ubuntu-latest"]}}}
    if local_context:
        manifest["local_context"] = local_context
    engineering.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(yaml.safe_dump(manifest, sort_keys=False), encoding="utf-8")
    generated = render_files(root, manifest)
    destination = engineering / "skills"
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(skills_root(), destination)
    generated.update({_relative_posix(p, root): digest_file(p) for p in destination.rglob("*") if p.is_file()})
    snapshot = {"core": core, "profile": selected_profile, "delivery_profiles": delivery}
    snapshot_path = engineering / "generated" / "resolved-policy.json"
    write_json(snapshot_path, snapshot)
    generated[_relative_posix(snapshot_path, root)] = digest_file(snapshot_path)
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(_workflow_text(revision), encoding="utf-8")
    generated[_relative_posix(workflow, root)] = digest_file(workflow)
    lock = {"schema_version": 1, "source": manifest["process"]["source"], "version": process_version, "revision": revision,
            "manifest_digest": digest_bytes(canonical_json(manifest).encode()), "policy_digest": digest_bytes(canonical_json(snapshot).encode()),
            "generated_at": datetime.now(timezone.utc).isoformat(), "generated_files": generated}
    write_json(engineering / "process.lock", lock)
    return {"created": [".engineering/process.yaml", ".engineering/process.lock", "AGENTS.md", "CLAUDE.md", ".github/workflows/process-validation.yml"],
            "preserved_context": [item["path"] for item in local_context], "skills": len(list(destination.glob("*/SKILL.md")))}


def manifest_digest(manifest: dict) -> str:
    return digest_bytes(canonical_json(manifest).encode())


def _migrate_manifest_v2(manifest: dict) -> dict:
    if manifest.get("schema_version") != 1:
        return manifest
    manifest["schema_version"] = 2
    overrides = manifest.setdefault("overrides", {})
    technology = overrides.pop("technology", None)
    if technology is not None:
        overrides.setdefault("extensions", []).append({"namespace": "legacy/technology", "schema_version": 1, "configuration": technology})
    legacy_native = overrides.pop("native_enforcement", {})
    checks = legacy_native.get("required_status_checks", ["engineering-process"])
    manifest.setdefault("adoption", {"target_mode": "Foundation", "metrics_enabled": False})
    manifest.setdefault("adapters", {})["github"] = {
        "readiness_status": checks[0] if checks else "engineering-process", "protected_branch": "main",
        "production_environment": "production", "runner_labels": ["ubuntu-latest"]}
    return manifest


def _flatten(value, prefix="") -> dict[str, object]:
    if isinstance(value, dict):
        return {k: v for key, item in value.items() for k, v in _flatten(item, f"{prefix}.{key}" if prefix else key).items()}
    if isinstance(value, list):
        return {prefix: tuple(value)}
    return {prefix: value}


def upgrade_report(root: Path, version: str, revision: str) -> dict:
    manifest = load_yaml(root / ".engineering" / "process.yaml")
    old_snapshot_path = root / ".engineering" / "generated" / "resolved-policy.json"
    old_snapshot = __import__("json").loads(old_snapshot_path.read_text()) if old_snapshot_path.exists() else {}
    core, profile, delivery = load_policy(policy_root(), manifest["process"]["profile"])
    if version != core["process"]["version"]:
        raise ProcessError(f"requested version {version} does not match installed process {core['process']['version']}")
    validate_overrides(core, manifest)
    new_snapshot = {"core": core, "profile": profile, "delivery_profiles": delivery}
    old, new = _flatten(old_snapshot), _flatten(new_snapshot)
    changes = [{"path": key, "before": old.get(key), "after": new.get(key)} for key in sorted(set(old) | set(new)) if old.get(key) != new.get(key)]
    locked = [c for c in changes if c["path"].startswith("core.controls.") and ".semantics" not in c["path"] and any(c["path"].startswith(f"core.controls.{name}.") for name, rule in core["controls"].items() if rule["semantics"] == "locked")]
    proposed_manifest = {**manifest, "process": {**manifest["process"], "version": version, "revision": revision}}
    from .render import bootstrap
    generated_changes = []
    for name, assistant in (("AGENTS.md", "codex"), ("CLAUDE.md", "claude")):
        path = root / name
        status = "modified" if not path.exists() or path.read_text(encoding="utf-8") != bootstrap(proposed_manifest, assistant) else "unchanged"
        generated_changes.append({"path": name, "status": status})
    desired_scoped = {f".github/instructions/{item['name']}.instructions.md" for item in proposed_manifest.get("adapters", {}).get("github_copilot", {}).get("scoped_instructions", [])}
    existing_scoped = set(load_json(root / ".engineering/process.lock").get("generated_files", {})) if (root / ".engineering/process.lock").exists() else set()
    for path in sorted(desired_scoped | {p for p in existing_scoped if p.startswith(".github/instructions/") and p.endswith(".instructions.md")}):
        generated_changes.append({"path": path, "status": "generated" if path in desired_scoped else "removed"})
    return {"current": manifest["process"], "proposed": proposed_manifest["process"],
            "inherited_rule_changes": changes, "new_locked_rule_changes": locked,
            "override_conflicts": [], "generated_files_change": generated_changes + [{"path": ".engineering/skills/*", "status": "refreshed"}, {"path": ".github/workflows/process-validation.yml", "status": "review"}],
            "preserved_local_context": [item["path"] for item in manifest.get("local_context", [])],
            "new_requirements": [c for c in changes if "required" in c["path"]], "requires_validation": True}


def apply_upgrade(root: Path, version: str, revision: str) -> dict:
    report = upgrade_report(root, version, revision)
    manifest = load_yaml(root / ".engineering" / "process.yaml")
    previous_schema = manifest.get("schema_version", 1)
    manifest = _migrate_manifest_v2(manifest)
    lock_path = root / ".engineering/process.lock"
    lock = __import__("json").loads(lock_path.read_text())
    old_generated = set(lock.get("generated_files", {}))
    for relative in old_generated:
        _assert_owned(root, lock, relative)
    manifest["process"].update({"version": version, "revision": revision})
    core, selected_profile, delivery = load_policy(policy_root(), manifest["process"]["profile"])
    generated = render_files(root, manifest, allow_create=False)
    removed = []
    for relative in sorted(old_generated - set(generated)):
        if relative.startswith(".github/instructions/") and relative.endswith(".instructions.md"):
            path = root / relative
            if path.exists() and path.read_text(encoding="utf-8").startswith("<!-- GENERATED BY software-engineering-process"):
                path.unlink(); removed.append(relative)
    destination = root / ".engineering/skills"
    shutil.rmtree(destination)
    shutil.copytree(skills_root(), destination)
    generated.update({_relative_posix(p, root): digest_file(p) for p in destination.rglob("*") if p.is_file()})
    snapshot = {"core": core, "profile": selected_profile, "delivery_profiles": delivery}
    snapshot_path = root / ".engineering/generated/resolved-policy.json"
    write_json(snapshot_path, snapshot)
    generated[_relative_posix(snapshot_path, root)] = digest_file(snapshot_path)
    workflow = root / ".github/workflows/process-validation.yml"
    workflow.write_text(_workflow_text(revision), encoding="utf-8")
    generated[_relative_posix(workflow, root)] = digest_file(workflow)
    manifest_path = root / ".engineering/process.yaml"
    manifest_path.write_text(yaml.safe_dump(manifest, sort_keys=False), encoding="utf-8")
    new_lock = {"schema_version": 1, "source": manifest["process"]["source"], "version": version, "revision": revision,
                "manifest_digest": manifest_digest(manifest), "policy_digest": digest_bytes(canonical_json(snapshot).encode()),
                "generated_at": datetime.now(timezone.utc).isoformat(), "generated_files": generated}
    write_json(lock_path, new_lock)
    return {**report, "applied": True, "preserved_context": report["preserved_local_context"], "removed_generated_adapters": removed,
            "schema_migration": f"v{previous_schema}->v2" if previous_schema != 2 else None}
